// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKahk0QCx3OCwgaDVuc8OgzBhJmWoBj-I',
    appId: '1:472410946370:android:126edb369b3ef0feb3e6db',
    messagingSenderId: '472410946370',
    projectId: 'we-chat-b07f4',
    storageBucket: 'we-chat-b07f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPolFbjncsB2Pyh6Oe9qrhB8Y8d1qKDG8',
    appId: '1:472410946370:ios:f5c803c12b48c50ab3e6db',
    messagingSenderId: '472410946370',
    projectId: 'we-chat-b07f4',
    storageBucket: 'we-chat-b07f4.appspot.com',
    androidClientId: '472410946370-f3ds2r35c56tbnpi3na9gsrgv6ccvq4p.apps.googleusercontent.com',
    iosClientId: '472410946370-rrvm7fjsrv3tq2eh766bvqucj6hacsiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79pFF4g9bTtlXDampQbwquyva8Z3tmwE',
    appId: '1:472410946370:web:a06a23a916611e3cb3e6db',
    messagingSenderId: '472410946370',
    projectId: 'we-chat-b07f4',
    authDomain: 'we-chat-b07f4.firebaseapp.com',
    storageBucket: 'we-chat-b07f4.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPolFbjncsB2Pyh6Oe9qrhB8Y8d1qKDG8',
    appId: '1:472410946370:ios:f5c803c12b48c50ab3e6db',
    messagingSenderId: '472410946370',
    projectId: 'we-chat-b07f4',
    storageBucket: 'we-chat-b07f4.appspot.com',
    androidClientId: '472410946370-f3ds2r35c56tbnpi3na9gsrgv6ccvq4p.apps.googleusercontent.com',
    iosClientId: '472410946370-rrvm7fjsrv3tq2eh766bvqucj6hacsiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA79pFF4g9bTtlXDampQbwquyva8Z3tmwE',
    appId: '1:472410946370:web:1e77d716e0514835b3e6db',
    messagingSenderId: '472410946370',
    projectId: 'we-chat-b07f4',
    authDomain: 'we-chat-b07f4.firebaseapp.com',
    storageBucket: 'we-chat-b07f4.appspot.com',
  );

}